services:
  postgres:
    image: postgres:15-alpine
    container_name: polypost_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: polypost_admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: polypost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polypost_admin -d polypost_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: polypost_redis
    ports:
      - "6379:6379"

  backend:
    build: ./server
    container_name: polypost_backend
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
      PORT: 4000
      DATABASE_URL: "postgresql://polypost_admin:securepassword123@postgres:5432/polypost_db?schema=public"
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLIENT_URL: "http://localhost:3000"

  frontend:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_API_URL: "http://localhost:4000"
    container_name: polypost_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: